document.addEventListener("DOMContentLoaded", function(event) {
	var random_country = countries[Math.floor(Math.random() * 252)]
	// console.log(document.getElementById("flag"))
	document.getElementById("flag").className += random_country.country_code
	document.getElementById("label").innerHTML = random_country.country_name
});

var countries = [{country_name: 'Andorra,', country_code: 'ad'}, {country_name: 'United Arab Emirates', country_code: 'ae'},
				{country_name: 'Afghanistan', country_code: 'af'}, {country_name: 'Antigua And Barbuda', country_code: 'ag'},
				{country_name: 'Anguilla', country_code: 'ai'}, {country_name: 'Albania', country_code: 'al'},
				{country_name: 'Armenia', country_code: 'am'}, {country_name: 'Netherlands Antilles', country_code: 'an'},
				{country_name: 'Angola', country_code: 'ao'}, {country_name: 'Argentina', country_code: 'ar'},
				{country_name: 'American Samoa', country_code: 'as'}, {country_name: 'Austria', country_code: 'at'},
				{country_name: 'Australia', country_code: 'au'}, {country_name: 'Aruba', country_code: 'aw'},
				{country_name: 'Aaland', country_code: 'ax'}, {country_name: 'Azerbaijan', country_code: 'az'},
				{country_name: 'Bosnia And Herzegovina', country_code: 'ba'}, {country_name: 'Basque', country_code: 'basque'},
				{country_name: 'Barbados', country_code: 'bb'}, {country_name: 'Bangladesh', country_code: 'bd'},
				{country_name: 'Belgium', country_code: 'be'}, {country_name: 'Burkina Faso', country_code: 'bf'},
				{country_name: 'Bulgaria', country_code: 'bg'}, {country_name: 'Bahrain', country_code: 'bh'},
				{country_name: 'Burundi', country_code: 'bi'}, {country_name: 'Benin', country_code: 'bj'},
				{country_name: 'Bermuda', country_code: 'bm'}, {country_name: 'Brunei', country_code: 'bn'},
				{country_name: 'Bolivia', country_code: 'bo'}, {country_name: 'Brazil', country_code: 'br'},
				{country_name: 'Bahamas', country_code: 'bs'}, {country_name: 'Bhutan', country_code: 'bt'},
				{country_name: 'Bouvet Island', country_code: 'bv'}, {country_name: 'Botswana', country_code: 'bw'},
				{country_name: 'Belarus', country_code: 'by'}, {country_name: 'Belize', country_code: 'bz'},
				{country_name: 'Canada', country_code: 'ca'}, {country_name: 'Catalonia', country_code: 'catalonia'},
				{country_name: 'Cocos Islands', country_code: 'cc'}, {country_name: 'Democratic Republic Of Congo', country_code: 'cd'},
				{country_name: 'Central African Republic', country_code: 'cf'}, {country_name: 'Congo', country_code: 'cg'},
				{country_name: 'Switzerland', country_code: 'ch'}, {country_name: 'Cote D\'ivoire', country_code: 'ci'},
				{country_name: 'Cook Islands', country_code: 'ck'}, {country_name: 'Chile', country_code: 'cl'},
				{country_name: 'Cameroon', country_code: 'cm'}, {country_name: 'China', country_code: 'cn'},
				{country_name: 'Colombia', country_code: 'co'}, {country_name: 'Costa Rica', country_code: 'cr'},
				{country_name: 'Serbia And Montenegro', country_code: 'cs'}, {country_name: 'Cuba', country_code: 'cu'},
				{country_name: 'Cape Verde', country_code: 'cv'}, {country_name: 'Christmas Island', country_code: 'cx'},
				{country_name: 'Cyprus', country_code: 'cy'}, {country_name: 'Czech Republic', country_code: 'cz'},
				{country_name: 'Germany', country_code: 'de'}, {country_name: 'Djibouti', country_code: 'dj'},
				{country_name: 'Denmark', country_code: 'dk'}, {country_name: 'Dominica', country_code: 'dm'},
				{country_name: 'Dominican Republic', country_code: 'do'}, {country_name: 'Algeria', country_code: 'dz'},
				{country_name: 'Ecuador', country_code: 'ec'}, {country_name: 'Estonia', country_code: 'ee'},
				{country_name: 'Egypt', country_code: 'eg'}, {country_name: 'Western Sahara', country_code: 'eh'},
				{country_name: 'England', country_code: 'england'}, {country_name: 'Eritrea', country_code: 'er'},
				{country_name: 'Spain', country_code: 'es'}, {country_name: 'Ethiopia', country_code: 'et'},
				{country_name: 'Europe', country_code: 'eu'}, {country_name: 'Finland', country_code: 'fi'},
				{country_name: 'Fiji', country_code: 'fj'}, {country_name: 'Falkland Islands', country_code: 'fk'},
				{country_name: 'Federated States Of Micronesia', country_code: 'fm'}, {country_name: 'Faroe Islands', country_code: 'fo'},
				{country_name: 'France', country_code: 'fr'}, {country_name: 'Gabon', country_code: 'ga'},
				{country_name: 'Galicia', country_code: 'galicia'}, {country_name: 'United Kingdom', country_code: 'gb'},
				{country_name: 'Grenada', country_code: 'gd'}, {country_name: 'Georgia', country_code: 'ge'},
				{country_name: 'French Guiana', country_code: 'gf'}, {country_name: 'Guernsey', country_code: 'gg'},
				{country_name: 'Ghana', country_code: 'gh'}, {country_name: 'Gibraltar', country_code: 'gi'},
				{country_name: 'Greenland', country_code: 'gl'}, {country_name: 'Gambia', country_code: 'gm'},
				{country_name: 'Guinea', country_code: 'gn'}, {country_name: 'Guadeloupe', country_code: 'gp'},
				{country_name: 'Equatorial Guinea', country_code: 'gq'}, {country_name: 'Greece', country_code: 'gr'},
				{country_name: 'South Georgia And South Sandwich Islands', country_code: 'gs'},
				{country_name: 'Guatemala', country_code: 'gt'}, {country_name: 'Guam', country_code: 'gu'},
				{country_name: 'Guinea-bissau', country_code: 'gw'}, {country_name: 'Guyana', country_code: 'gy'},
				{country_name: 'Hong Kong', country_code: 'hk'}, {country_name: 'Heard Island And Mcdonald Slands', country_code: 'hm'},
				{country_name: 'Honduras', country_code: 'hn'}, {country_name: 'Croatia', country_code: 'hr'},
				{country_name: 'Haiti', country_code: 'ht'}, {country_name: 'Hungary', country_code: 'hu'},
				{country_name: 'Indonesia', country_code: 'id'}, {country_name: 'Ireland', country_code: 'ie'},
				{country_name: 'Israel', country_code: 'il'}, {country_name: 'Isle Of Man', country_code: 'im'},
				{country_name: 'India', country_code: 'in'}, {country_name: 'British Indian Ocean Territory', country_code: 'io'},
				{country_name: 'Iraq', country_code: 'iq'}, {country_name: 'Iran', country_code: 'ir'},
				{country_name: 'Iceland', country_code: 'is'}, {country_name: 'Italy', country_code: 'it'},
				{country_name: 'Jersey', country_code: 'je'}, {country_name: 'Jamaica', country_code: 'jm'},
				{country_name: 'Jordan', country_code: 'jo'}, {country_name: 'Japan', country_code: 'jp'},
				{country_name: 'Kenya', country_code: 'ke'}, {country_name: 'Kyrgyzstan', country_code: 'kg'},
				{country_name: 'Cambodia', country_code: 'kh'}, {country_name: 'Kiribati', country_code: 'ki'},
				{country_name: 'Comoros', country_code: 'km'}, {country_name: 'Saint Kitts And Nevis', country_code: 'kn'},
				{country_name: 'North Korea', country_code: 'kp'}, {country_name: 'South Korea', country_code: 'kr'},
				{country_name: 'Kuwait', country_code: 'kw'}, {country_name: 'Cayman Islands', country_code: 'ky'},
				{country_name: 'Kazakhstan', country_code: 'kz'}, {country_name: 'Laos', country_code: 'la'},
				{country_name: 'Lebanon', country_code: 'lb'}, {country_name: 'Saint Lucia', country_code: 'lc'},
				{country_name: 'Liechtenstein', country_code: 'li'}, {country_name: 'Sri Lanka', country_code: 'lk'},
				{country_name: 'Liberia', country_code: 'lr'}, {country_name: 'Lesotho', country_code: 'ls'},
				{country_name: 'Lithuania', country_code: 'lt'}, {country_name: 'Luxembourg', country_code: 'lu'},
				{country_name: 'Latvia', country_code: 'lv'}, {country_name: 'Libya', country_code: 'ly'},
				{country_name: 'Morocco', country_code: 'ma'}, {country_name: 'Monaco', country_code: 'mc'},
				{country_name: 'Moldova', country_code: 'md'}, {country_name: 'Montenegro', country_code: 'me'},
				{country_name: 'Saint Martin', country_code: 'mf'}, {country_name: 'Madagascar', country_code: 'mg'},
				{country_name: 'Marshall Islands', country_code: 'mh'}, {country_name: 'Macedonia', country_code: 'mk'},
				{country_name: 'Mali', country_code: 'ml'}, {country_name: 'Myanmar', country_code: 'mm'},
				{country_name: 'Mongolia', country_code: 'mn'}, {country_name: 'Macau', country_code: 'mo'},
				{country_name: 'Northern Mariana Islands', country_code: 'mp'}, {country_name: 'Martinique', country_code: 'mq'},
				{country_name: 'Mauritania', country_code: 'mr'}, {country_name: 'Montserrat', country_code: 'ms'},
				{country_name: 'Malta', country_code: 'mt'}, {country_name: 'Mauritius', country_code: 'mu'},
				{country_name: 'Maldives', country_code: 'mv'}, {country_name: 'Malawi', country_code: 'mw'},
				{country_name: 'Mexico', country_code: 'mx'}, {country_name: 'Malaysia', country_code: 'my'},
				{country_name: 'Mozambique', country_code: 'mz'}, {country_name: 'Namibia', country_code: 'na'},
				{country_name: 'New Caledonia', country_code: 'nc'}, {country_name: 'Niger', country_code: 'ne'},
				{country_name: 'Norfolk Island', country_code: 'nf'}, {country_name: 'Nigeria', country_code: 'ng'},
				{country_name: 'Nicaragua', country_code: 'ni'}, {country_name: 'Netherlands', country_code: 'nl'},
				{country_name: 'Norway', country_code: 'no'}, {country_name: 'Nepal', country_code: 'np'},
				{country_name: 'Nauru', country_code: 'nr'}, {country_name: 'Niue', country_code: 'nu'},
				{country_name: 'New Zealand', country_code: 'nz'}, {country_name: 'Oman', country_code: 'om'},
				{country_name: 'Panama', country_code: 'pa'}, {country_name: 'Peru', country_code: 'pe'},
				{country_name: 'French Polynesia', country_code: 'pf'}, {country_name: 'Papua New Guinea', country_code: 'pg'},
				{country_name: 'Philippines', country_code: 'ph'}, {country_name: 'Pakistan', country_code: 'pk'},
				{country_name: 'Poland', country_code: 'pl'}, {country_name: 'Saint-pierre And Miquelon', country_code: 'pm'},
				{country_name: 'Pitcairn Islands', country_code: 'pn'}, {country_name: 'Puerto Rico', country_code: 'pr'},
				{country_name: 'Palestine', country_code: 'ps'}, {country_name: 'Portugal', country_code: 'pt'},
				{country_name: 'Palau', country_code: 'pw'}, {country_name: 'Paraguay', country_code: 'py'},
				{country_name: 'Qatar', country_code: 'qa'}, {country_name: 'Reunion', country_code: 're'},
				{country_name: 'Romania', country_code: 'ro'}, {country_name: 'Serbia', country_code: 'rs'},
				{country_name: 'Russia', country_code: 'ru'}, {country_name: 'Rwanda', country_code: 'rw'},
				{country_name: 'Saudi Arabia', country_code: 'sa'}, {country_name: 'Solomon Islands', country_code: 'sb'},
				{country_name: 'Seychelles', country_code: 'sc'}, {country_name: 'Scotland', country_code: 'scotland'},
				{country_name: 'Sudan', country_code: 'sd'}, {country_name: 'Sweden', country_code: 'se'},
				{country_name: 'Singapore', country_code: 'sg'}, {country_name: 'Saint Helena', country_code: 'sh'},
				{country_name: 'Slovenia', country_code: 'si'}, {country_name: 'Svalbard And Jan Mayen', country_code: 'sj'},
				{country_name: 'Slovakia', country_code: 'sk'}, {country_name: 'Sierra Leone', country_code: 'sl'},
				{country_name: 'San Marino', country_code: 'sm'}, {country_name: 'Senegal', country_code: 'sn'},
				{country_name: 'Somalia', country_code: 'so'}, {country_name: 'Suriname', country_code: 'sr'},
				{country_name: 'Sao Tome And Principe', country_code: 'st'}, {country_name: 'El Salvador', country_code: 'sv'},
				{country_name: 'Syria', country_code: 'sy'}, {country_name: 'Swaziland', country_code: 'sz'},
				{country_name: 'Turks And Caicos Islands', country_code: 'tc'}, {country_name: 'Chad', country_code: 'td'},
				{country_name: 'French Southern And Antarctic Lands', country_code: 'tf'}, {country_name: 'Togo', country_code: 'tg'},
				{country_name: 'Thailand', country_code: 'th'}, {country_name: 'Tajikistan', country_code: 'tj'},
				{country_name: 'Tokelau', country_code: 'tk'}, {country_name: 'East Timor', country_code: 'tm'},
				{country_name: 'Turkmenistan', country_code: 'tm'}, {country_name: 'Tunisia', country_code: 'tn'},
				{country_name: 'Tonga', country_code: 'to'}, {country_name: 'Turkey', country_code: 'tr'},
				{country_name: 'Trinidad And Tobago', country_code: 'tt'}, {country_name: 'Tuvalu', country_code: 'tv'},
				{country_name: 'Republic Of China Taiwan', country_code: 'tw'}, {country_name: 'Tanzania', country_code: 'tz'},
				{country_name: 'Ukraine', country_code: 'ua'}, {country_name: 'Uganda', country_code: 'ug'},
				{country_name: 'United States Minor Outlying Islands', country_code: 'um'},
				{country_name: 'United States', country_code: 'us'}, {country_name: 'Uruguay', country_code: 'uy'},
				{country_name: 'Uzbekistan', country_code: 'uz'}, {country_name: 'Vatican City', country_code: 'va'},
				{country_name: 'Saint Vincent And Grenadines', country_code: 'vc'}, {country_name: 'Venezuela', country_code: 've'},
				{country_name: 'British Virgin Islands', country_code: 'vg'},
				{country_name: 'United States Virgin Islands', country_code: 'vi'},
				{country_name: 'Vietnam', country_code: 'vn'}, {country_name: 'Vanuatu', country_code: 'vu'},
				{country_name: 'Wales', country_code: 'wales'}, {country_name: 'Wallis And Futuna', country_code: 'wf'},
				{country_name: 'Samoa', country_code: 'ws'}, {country_name: 'Yemen', country_code: 'ye'},
				{country_name: 'Mayotte', country_code: 'yt'}, {country_name: 'South Africa', country_code: 'za'},
				{country_name: 'Zambia', country_code: 'zm'}, {country_name: 'Zimbabwe', country_code: 'zw'}]				