document.addEventListener("DOMContentLoaded", function(event) {
	var random_country = countries[Math.floor(Math.random() * countries.length)]
	document.getElementById("flag").className += random_country.key
	document.getElementById("label").innerHTML = random_country.display_name

});

// document.addEventListener("DOMContentLoaded", function(event) {
// 	document.getElementById("flag").className += 'gb'
// 	document.getElementById("label").innerHTML = 'United Kingdom'
// });

chrome.storage.sync.get(function(data) {
	if (data.showLabels || data.showLabels == undefined) {
		document.getElementById("label").style.display = "block"
	}
})

var countries = [{display_name: 'Andorra', key: 'ad'}, {display_name: 'United Arab Emirates', key: 'ae'},
				{display_name: 'Afghanistan', key: 'af'}, {display_name: 'Antigua and Barbuda', key: 'ag'},
				{display_name: 'Anguilla', key: 'ai'}, {display_name: 'Albania', key: 'al'},
				{display_name: 'Armenia', key: 'am'},
				{display_name: 'Angola', key: 'ao'}, {display_name: 'Argentina', key: 'ar'},
				{display_name: 'American Samoa', key: 'as'}, {display_name: 'Austria', key: 'at'},
				{display_name: 'Australia', key: 'au'}, {display_name: 'Aruba', key: 'aw'},
				{display_name: '&Aring;land Islands', key: 'ax'}, {display_name: 'Azerbaijan', key: 'az'},
				{display_name: 'Bosnia and Herzegovina', key: 'ba'}, {display_name: 'Basque', key: 'basque'},
				{display_name: 'Barbados', key: 'bb'}, {display_name: 'Bangladesh', key: 'bd'},
				{display_name: 'Belgium', key: 'be'}, {display_name: 'Burkina Faso', key: 'bf'},
				{display_name: 'Bulgaria', key: 'bg'}, {display_name: 'Bahrain', key: 'bh'},
				{display_name: 'Burundi', key: 'bi'}, {display_name: 'Benin', key: 'bj'},
				{display_name: 'Bermuda', key: 'bm'}, {display_name: 'Brunei', key: 'bn'},
				{display_name: 'Bolivia', key: 'bo'}, {display_name: 'Brazil', key: 'br'},
				{display_name: 'The Bahamas', key: 'bs'}, {display_name: 'Bhutan', key: 'bt'},
				{display_name: 'Bouvet Island', key: 'bv'}, {display_name: 'Botswana', key: 'bw'},
				{display_name: 'Belarus', key: 'by'}, {display_name: 'Belize', key: 'bz'},
				{display_name: 'Canada', key: 'ca'}, {display_name: 'Catalonia', key: 'catalonia'},
				{display_name: 'Cocos Islands', key: 'cc'}, {display_name: 'Democratic Republic of the Congo', key: 'cd'},
				{display_name: 'Central African Republic', key: 'cf'}, {display_name: 'Congo', key: 'cg'},
				{display_name: 'Switzerland', key: 'ch'}, {display_name: 'C&ocirc;te d\'Ivoire (Ivory Coast)', key: 'ci'},
				{display_name: 'Cook Islands', key: 'ck'}, {display_name: 'Chile', key: 'cl'},
				{display_name: 'Cameroon', key: 'cm'}, {display_name: 'People\'s Republic of China', key: 'cn'},
				{display_name: 'Colombia', key: 'co'}, {display_name: 'Costa Rica', key: 'cr'},
				{display_name: 'Cuba', key: 'cu'},
				{display_name: 'Cape Verde', key: 'cv'}, {display_name: 'Christmas Island', key: 'cx'},
				{display_name: 'Cyprus', key: 'cy'}, {display_name: 'Czech Republic', key: 'cz'},
				{display_name: 'Germany', key: 'de'}, {display_name: 'Djibouti', key: 'dj'},
				{display_name: 'Denmark', key: 'dk'}, {display_name: 'Dominica', key: 'dm'},
				{display_name: 'Dominican Republic', key: 'do'}, {display_name: 'Algeria', key: 'dz'},
				{display_name: 'Ecuador', key: 'ec'}, {display_name: 'Estonia', key: 'ee'},
				{display_name: 'Egypt', key: 'eg'},
				{display_name: 'England', key: 'england'}, {display_name: 'Eritrea', key: 'er'},
				{display_name: 'Spain', key: 'es'}, {display_name: 'Ethiopia', key: 'et'},
				{display_name: 'European Union', key: 'eu'}, {display_name: 'Finland', key: 'fi'},
				{display_name: 'Fiji', key: 'fj'}, {display_name: 'Falkland Islands', key: 'fk'},
				{display_name: 'Federated States of Micronesia', key: 'fm'}, {display_name: 'Faroe Islands', key: 'fo'},
				{display_name: 'France', key: 'fr'}, {display_name: 'Gabon', key: 'ga'},
				{display_name: 'Galicia', key: 'galicia'}, {display_name: 'United Kingdom', key: 'gb'},
				{display_name: 'Grenada', key: 'gd'}, {display_name: 'Georgia', key: 'ge'},
				{display_name: 'French Guiana', key: 'gf'}, {display_name: 'Guernsey', key: 'gg'},
				{display_name: 'Ghana', key: 'gh'}, {display_name: 'Gibraltar', key: 'gi'},
				{display_name: 'Greenland', key: 'gl'}, {display_name: 'The Gambia', key: 'gm'},
				{display_name: 'Guinea', key: 'gn'}, {display_name: 'Guadeloupe', key: 'gp'},
				{display_name: 'Equatorial Guinea', key: 'gq'}, {display_name: 'Greece', key: 'gr'},
				{display_name: 'South Georgia and the South Sandwich Islands', key: 'gs'},
				{display_name: 'Guatemala', key: 'gt'}, {display_name: 'Guam', key: 'gu'},
				{display_name: 'Guinea-Bissau', key: 'gw'}, {display_name: 'Guyana', key: 'gy'},
				{display_name: 'Hong Kong', key: 'hk'}, {display_name: 'Heard Island and Mcdonald Islands', key: 'hm'},
				{display_name: 'Honduras', key: 'hn'}, {display_name: 'Croatia', key: 'hr'},
				{display_name: 'Haiti', key: 'ht'}, {display_name: 'Hungary', key: 'hu'},
				{display_name: 'Indonesia', key: 'id'}, {display_name: 'Ireland', key: 'ie'},
				{display_name: 'Israel', key: 'il'}, {display_name: 'Isle of Man', key: 'im'},
				{display_name: 'India', key: 'in'}, {display_name: 'British Indian Ocean Territory', key: 'io'},
				{display_name: 'Iraq', key: 'iq'}, {display_name: 'Iran', key: 'ir'},
				{display_name: 'Iceland', key: 'is'}, {display_name: 'Italy', key: 'it'},
				{display_name: 'Jersey', key: 'je'}, {display_name: 'Jamaica', key: 'jm'},
				{display_name: 'Jordan', key: 'jo'}, {display_name: 'Japan', key: 'jp'},
				{display_name: 'Kenya', key: 'ke'}, {display_name: 'Kyrgyzstan', key: 'kg'},
				{display_name: 'Cambodia', key: 'kh'}, {display_name: 'Kiribati', key: 'ki'},
				{display_name: 'Comoros', key: 'km'}, {display_name: 'Saint Kitts and Nevis', key: 'kn'},
				{display_name: 'North Korea', key: 'kp'}, {display_name: 'South Korea', key: 'kr'},
				{display_name: 'Kuwait', key: 'kw'}, {display_name: 'Cayman Islands', key: 'ky'},
				{display_name: 'Kazakhstan', key: 'kz'}, {display_name: 'Laos', key: 'la'},
				{display_name: 'Lebanon', key: 'lb'}, {display_name: 'Saint Lucia', key: 'lc'},
				{display_name: 'Liechtenstein', key: 'li'}, {display_name: 'Sri Lanka', key: 'lk'},
				{display_name: 'Liberia', key: 'lr'}, {display_name: 'Lesotho', key: 'ls'},
				{display_name: 'Lithuania', key: 'lt'}, {display_name: 'Luxembourg', key: 'lu'},
				{display_name: 'Latvia', key: 'lv'}, {display_name: 'Libya', key: 'ly'},
				{display_name: 'Morocco', key: 'ma'}, {display_name: 'Monaco', key: 'mc'},
				{display_name: 'Moldova', key: 'md'}, {display_name: 'Montenegro', key: 'me'},
				{display_name: 'Saint Martin', key: 'mf'}, {display_name: 'Madagascar', key: 'mg'},
				{display_name: 'Marshall Islands', key: 'mh'}, {display_name: 'Macedonia', key: 'mk'},
				{display_name: 'Mali', key: 'ml'}, {display_name: 'Myanmar (Burma)', key: 'mm'},
				{display_name: 'Mongolia', key: 'mn'}, {display_name: 'Macau', key: 'mo'},
				{display_name: 'Northern Mariana Islands', key: 'mp'}, {display_name: 'Martinique', key: 'mq'},
				{display_name: 'Mauritania', key: 'mr'}, {display_name: 'Montserrat', key: 'ms'},
				{display_name: 'Malta', key: 'mt'}, {display_name: 'Mauritius', key: 'mu'},
				{display_name: 'Maldives', key: 'mv'}, {display_name: 'Malawi', key: 'mw'},
				{display_name: 'Mexico', key: 'mx'}, {display_name: 'Malaysia', key: 'my'},
				{display_name: 'Mozambique', key: 'mz'}, {display_name: 'Namibia', key: 'na'},
				{display_name: 'New Caledonia', key: 'nc'}, {display_name: 'Niger', key: 'ne'},
				{display_name: 'Norfolk Island', key: 'nf'}, {display_name: 'Nigeria', key: 'ng'},
				{display_name: 'Nicaragua', key: 'ni'}, {display_name: 'Netherlands', key: 'nl'},
				{display_name: 'Norway', key: 'no'}, {display_name: 'Nepal', key: 'np'},
				{display_name: 'Nauru', key: 'nr'}, {display_name: 'Niue', key: 'nu'},
				{display_name: 'New Zealand', key: 'nz'}, {display_name: 'Oman', key: 'om'},
				{display_name: 'Panama', key: 'pa'}, {display_name: 'Peru', key: 'pe'},
				{display_name: 'French Polynesia', key: 'pf'}, {display_name: 'Papua New Guinea', key: 'pg'},
				{display_name: 'Philippines', key: 'ph'}, {display_name: 'Pakistan', key: 'pk'},
				{display_name: 'Poland', key: 'pl'}, {display_name: 'Saint-Pierre and Miquelon', key: 'pm'},
				{display_name: 'Pitcairn Islands', key: 'pn'}, {display_name: 'Puerto Rico', key: 'pr'},
				{display_name: 'Palestine', key: 'ps'}, {display_name: 'Portugal', key: 'pt'},
				{display_name: 'Palau', key: 'pw'}, {display_name: 'Paraguay', key: 'py'},
				{display_name: 'Qatar', key: 'qa'}, {display_name: 'R&eacute;union', key: 're'},
				{display_name: 'Romania', key: 'ro'}, {display_name: 'Serbia', key: 'rs'},
				{display_name: 'Russia', key: 'ru'}, {display_name: 'Rwanda', key: 'rw'},
				{display_name: 'Saudi Arabia', key: 'sa'}, {display_name: 'Solomon Islands', key: 'sb'},
				{display_name: 'Seychelles', key: 'sc'}, {display_name: 'Scotland', key: 'scotland'},
				{display_name: 'Sudan', key: 'sd'}, {display_name: 'Sweden', key: 'se'},
				{display_name: 'Singapore', key: 'sg'}, {display_name: 'Saint Helena', key: 'sh'},
				{display_name: 'Slovenia', key: 'si'}, {display_name: 'Svalbard and Jan Mayen', key: 'sj'},
				{display_name: 'Slovakia', key: 'sk'}, {display_name: 'Sierra Leone', key: 'sl'},
				{display_name: 'San Marino', key: 'sm'}, {display_name: 'Senegal', key: 'sn'},
				{display_name: 'Somalia', key: 'so'}, {display_name: 'Suriname', key: 'sr'},
				{display_name: 'S&atilde;o Tom&eacute; and Pr&iacute;ncipe', key: 'st'}, {display_name: 'El Salvador', key: 'sv'},
				{display_name: 'Syria', key: 'sy'}, {display_name: 'Swaziland', key: 'sz'},
				{display_name: 'Turks and Caicos Islands', key: 'tc'}, {display_name: 'Chad', key: 'td'},
				{display_name: 'French Southern and Antarctic Lands', key: 'tf'}, {display_name: 'Togo', key: 'tg'},
				{display_name: 'Thailand', key: 'th'}, {display_name: 'Tajikistan', key: 'tj'},
				{display_name: 'Tokelau', key: 'tk'}, {display_name: 'Timor-Leste (East Timor)', key: 'timor'},
				{display_name: 'Turkmenistan', key: 'tm'}, {display_name: 'Tunisia', key: 'tn'},
				{display_name: 'Tonga', key: 'to'}, {display_name: 'Turkey', key: 'tr'},
				{display_name: 'Trinidad and Tobago', key: 'tt'}, {display_name: 'Tuvalu', key: 'tv'},
				{display_name: 'Republic of China (Taiwan)', key: 'tw'}, {display_name: 'Tanzania', key: 'tz'},
				{display_name: 'Ukraine', key: 'ua'}, {display_name: 'Uganda', key: 'ug'},
				{display_name: 'United States Minor Outlying Islands', key: 'um'},
				{display_name: 'United States of America', key: 'us'}, {display_name: 'Uruguay', key: 'uy'},
				{display_name: 'Uzbekistan', key: 'uz'}, {display_name: 'Vatican City', key: 'va'},
				{display_name: 'Saint Vincent and the Grenadines', key: 'vc'}, {display_name: 'Venezuela', key: 've'},
				{display_name: 'British Virgin Islands', key: 'vg'}, {display_name: 'United States Virgin Islands', key: 'vi'},
				{display_name: 'Vietnam', key: 'vn'}, {display_name: 'Vanuatu', key: 'vu'},
				{display_name: 'Wales', key: 'wales'}, {display_name: 'Wallis and Futuna', key: 'wf'},
				{display_name: 'Samoa', key: 'ws'}, {display_name: 'Yemen', key: 'ye'},
				{display_name: 'Mayotte', key: 'yt'}, {display_name: 'South Africa', key: 'za'},
				{display_name: 'Zambia', key: 'zm'}, {display_name: 'Zimbabwe', key: 'zw'},
				{display_name: 'Saint Barth&eacute;lemy', key: 'barthelemy'}, {display_name: 'Cura&ccedil;ao', key: 'curacao'},
				{display_name: 'South Sudan', key: 's_sudan'}, {display_name: 'British Antarctic Territory', key: 'uk_ant'},
				{display_name: 'Abkhazia', key: 'abkhazia'}, {display_name: 'Kosovo', key: 'kosovo'},
				{display_name: 'Nagorno-Karabakh', key: 'nkr'}, {display_name: 'Northern Cyprus', key: 'n_cyprus'},
				{display_name: 'Sahrawi Arab Democratic Republic', key: 'sadr'}, {display_name: 'South Ossetia', key: 's_ossetia'},
				{display_name: 'Transnistria', key: 'transnistria'}, {display_name: 'Somaliland', key: 'somaliland'},
				{display_name: 'Azad Kashmir', key: 'azad_kashmir'}, {display_name: 'Cyrenaica', key: 'cyrenaica'},
				{display_name: 'Syrian Kurdistan', key: 'syrian_kurdistan'}, {display_name: 'Sint Maarten', key: 'maarten'},
				{display_name: 'Iraqi Kurdistan', key: 'iraqi_kurdistan'}, {display_name: 'Crimea', key: 'crimea'}]




// {display_name: '', key: ''}



