var countries = [ { display_name: '&Aring;land Islands', key: 'aland_islands', wikiUrl: '/wiki/%C3%85land_Islands' }, //
  				  { display_name: 'Abkhazia', key: 'abkhazia', wikiUrl: '/wiki/Abkhazia' },
  				  { display_name: 'Afghanistan', key: 'afghanistan', wikiUrl: '/wiki/Afghanistan' },
  				  { display_name: 'Albania', key: 'albania', wikiUrl: '/wiki/Albania' },
  				  { display_name: 'Algeria', key: 'algeria', wikiUrl: '/wiki/Algeria' },
  				  { display_name: 'American Samoa', key: 'american_samoa', wikiUrl: '/wiki/American_Samoa' },
  				  { display_name: 'Andorra', key: 'andorra', wikiUrl: '/wiki/Andorra' },
  				  { display_name: 'Angola', key: 'angola', wikiUrl: '/wiki/Angola' },
  				  { display_name: 'Anguilla', key: 'anguilla', wikiUrl: '/wiki/Anguilla' },
  				  { display_name: 'Antigua and Barbuda', key: 'antigua_and_barbuda', wikiUrl: '/wiki/Antigua_and_Barbuda' },
  				  { display_name: 'Argentina', key: 'argentina', wikiUrl: '/wiki/Argentina' },
  				  { display_name: 'Armenia', key: 'armenia', wikiUrl: '/wiki/Armenia' },
  				  { display_name: 'Aruba', key: 'aruba', wikiUrl: '/wiki/Aruba' },//
  				  { display_name: 'Australia', key: 'australia', wikiUrl: '/wiki/Australia' },
  				  { display_name: 'Austria', key: 'austria', wikiUrl: '/wiki/Austria' },
  				  { display_name: 'Azad Kashmir', key: 'azad_kashmir', wikiUrl: '/wiki/Azad_Kashmir' },
  				  { display_name: 'Azerbaijan', key: 'azerbaijan', wikiUrl: '/wiki/Azerbaijan' },
  				  { display_name: 'Bahrain', key: 'bahrain', wikiUrl: '/wiki/Bahrain' },
  				  { display_name: 'Bangladesh', key: 'bangladesh', wikiUrl: '/wiki/Bangladesh' },
  				  { display_name: 'Barbados', key: 'barbados', wikiUrl: '/wiki/Barbados' },
  				  { display_name: 'Basque', key: 'basque', wikiUrl: '/wiki/Basque_Country_(autonomous_community)' },
  				  { display_name: 'Belarus', key: 'belarus', wikiUrl: '/wiki/Belarus' },
  				  { display_name: 'Belgium', key: 'belgium', wikiUrl: '/wiki/Belgium' },
  				  { display_name: 'Belize', key: 'belize', wikiUrl: '/wiki/Belize' },
  				  { display_name: 'Benin', key: 'benin', wikiUrl: '/wiki/Benin' },
  				  { display_name: 'Bermuda', key: 'bermuda', wikiUrl: '/wiki/Bermuda' },//
  				  { display_name: 'Bhutan', key: 'bhutan', wikiUrl: '/wiki/Bhutan' },
  				  { display_name: 'Bolivia', key: 'bolivia', wikiUrl: '/wiki/Bolivia' },
  				  { display_name: 'Bosnia and Herzegovina', key: 'bosnia_and_herzegovina', wikiUrl: '/wiki/Bosnia_and_Herzegovina' },
  				  { display_name: 'Botswana', key: 'botswana', wikiUrl: '/wiki/Botswana' },
  				  { display_name: 'Bouvet Island', key: 'bouvet_island', wikiUrl: '/wiki/Bouvet_Island' },//
  				  { display_name: 'Brazil', key: 'brazil', wikiUrl: '/wiki/Brazil' },
  				  { display_name: 'British Antarctic Territory', key: 'british_antarctic_territory', wikiUrl: '/wiki/British_Antarctic_Territory' },//
  				  { display_name: 'British Indian Ocean Territory', key: 'british_indian_ocean_territory', wikiUrl: '/wiki/British_Indian_Ocean_Territory' },//
  				  { display_name: 'British Virgin Islands', key: 'british_virgin_islands', wikiUrl: '/wiki/British_Virgin_Islands' },//
  				  { display_name: 'Brunei', key: 'brunei', wikiUrl: '/wiki/Brunei' },
  				  { display_name: 'Bulgaria', key: 'bulgaria', wikiUrl: '/wiki/Bulgaria' },
  				  { display_name: 'Burkina Faso', key: 'burkina_faso', wikiUrl: '/wiki/Burkina_Faso' },
  				  { display_name: 'Burundi', key: 'burundi', wikiUrl: '/wiki/Burundi' },
  				  { display_name: 'C&ocirc;te d\'Ivoire (Ivory Coast)', key: 'ivory_coast', wikiUrl: '/wiki/Ivory_Coast' },//
  				  { display_name: 'Cambodia', key: 'cambodia', wikiUrl: '/wiki/Cambodia' },
  				  { display_name: 'Cameroon', key: 'cameroon', wikiUrl: '/wiki/Cameroon' },
  				  { display_name: 'Canada', key: 'canada', wikiUrl: '/wiki/Canada' },
  				  { display_name: 'Cape Verde', key: 'cape_verde', wikiUrl: '/wiki/Cape_Verde' },
  				  { display_name: 'Catalonia', key: 'catalonia', wikiUrl: '/wiki/Catalonia' },//
  				  { display_name: 'Cayman Islands', key: 'cayman_islands', wikiUrl: '/wiki/Cayman_Islands' },//
  				  { display_name: 'Central African Republic', key: 'central_african_republic', wikiUrl: '/wiki/Central_African_Republic' },
  				  { display_name: 'Chad', key: 'chad', wikiUrl: '/wiki/Chad' },
  				  { display_name: 'Chile', key: 'chile', wikiUrl: '/wiki/Chile' },
  				  { display_name: 'Christmas Island', key: 'christmas_island', wikiUrl: '/wiki/Christmas_Island' },//
  				  { display_name: 'Cocos Islands', key: 'cocos_islands', wikiUrl: '/wiki/Cocos_(Keeling)_Islands' },//
  				  { display_name: 'Colombia', key: 'colombia', wikiUrl: '/wiki/Colombia' },
  				  { display_name: 'Comoros', key: 'comoros', wikiUrl: '/wiki/Comoros' },
  				  { display_name: 'Congo', key: 'congo', wikiUrl: '/wiki/Republic_of_the_Congo' },//
  				  { display_name: 'Cook Islands', key: 'cook_islands', wikiUrl: '/wiki/Cook_Islands' },
  				  { display_name: 'Costa Rica', key: 'costa_rica', wikiUrl: '/wiki/Costa_Rica' },
  				  { display_name: 'Crimea', key: 'crimea', wikiUrl: '/wiki/Republic_of_Crimea' },//
  				  { display_name: 'Croatia', key: 'croatia', wikiUrl: '/wiki/Croatia' },
  				  { display_name: 'Cuba', key: 'cuba', wikiUrl: '/wiki/Cuba' },
  				  { display_name: 'Cura&ccedil;ao', key: 'curacao', wikiUrl: '/wiki/Cura%C3%A7ao' },//
  				  { display_name: 'Cyprus', key: 'cyprus', wikiUrl: '/wiki/Cyprus' },
  				  { display_name: 'Cyrenaica', key: 'cyrenaica', wikiUrl: '/wiki/Cyrenaica' },//
  				  { display_name: 'Czech Republic', key: 'czech_republic', wikiUrl: '/wiki/Czech_Republic' },
  				  { display_name: 'Democratic Republic of the Congo', key: 'democratic_republic_of_the_congo', wikiUrl: '/wiki/Democratic_Republic_of_the_Congo' },
  				  { display_name: 'Denmark', key: 'denmark', wikiUrl: '/wiki/Denmark' },
  				  { display_name: 'Djibouti', key: 'djibouti', wikiUrl: '/wiki/Djibouti' },
  				  { display_name: 'Dominica', key: 'dominica', wikiUrl: '/wiki/Dominica' },
  				  { display_name: 'Dominican Republic', key: 'dominican_republic', wikiUrl: '/wiki/Dominican_Republic' },
  				  { display_name: 'Ecuador', key: 'ecuador', wikiUrl: '/wiki/Ecuador' },
  				  { display_name: 'Egypt', key: 'egypt', wikiUrl: '/wiki/Egypt' },
  				  { display_name: 'El Salvador', key: 'el_salvador', wikiUrl: '/wiki/El_Salvador' },
  				  { display_name: 'England', key: 'england', wikiUrl: '/wiki/England' },//
  				  { display_name: 'Equatorial Guinea', key: 'equatorial_guinea', wikiUrl: '/wiki/Equatorial_Guinea' },
  				  { display_name: 'Eritrea', key: 'eritrea', wikiUrl: '/wiki/Eritrea' },
  				  { display_name: 'Estonia', key: 'estonia', wikiUrl: '/wiki/Estonia' },
  				  { display_name: 'Ethiopia', key: 'ethiopia', wikiUrl: '/wiki/Ethiopia' },
  				  { display_name: 'European Union', key: 'european_union', wikiUrl: '/wiki/European_Union' },//
  				  { display_name: 'Falkland Islands', key: 'falkland_islands', wikiUrl: '/wiki/Falkland_Islands' },//
  				  { display_name: 'Faroe Islands', key: 'faroe_islands', wikiUrl: '/wiki/Faroe_Islands' },//
  				  { display_name: 'Federated States of Micronesia', key: 'federated_states_of_micronesia', wikiUrl: '/wiki/Micronesia' },//
  				  { display_name: 'Fiji', key: 'fiji', wikiUrl: '/wiki/Fiji' },
  				  { display_name: 'Finland', key: 'finland', wikiUrl: '/wiki/Finland' },
  				  { display_name: 'France', key: 'france', wikiUrl: '/wiki/France' },
  				  { display_name: 'French Guiana', key: 'french_guiana', wikiUrl: '/wiki/French_Guiana' },
  				  { display_name: 'French Polynesia', key: 'french_polynesia', wikiUrl: '/wiki/French_Polynesia' },
  				  { display_name: 'French Southern and Antarctic Lands', key: 'french_southern_and_antarctic_lands', wikiUrl: '/wiki/French_Southern_and_Antarctic_Lands' },
  				  { display_name: 'Gabon', key: 'gabon', wikiUrl: '/wiki/Gabon' },
  				  { display_name: 'Galicia', key: 'galicia', wikiUrl: '/wiki/Galicia_(Spain)' },
  				  { display_name: 'Georgia', key: 'georgia_country', wikiUrl: '/wiki/Georgia_(country)' },
  				  { display_name: 'Germany', key: 'germany', wikiUrl: '/wiki/Germany' },
  				  { display_name: 'Ghana', key: 'ghana', wikiUrl: '/wiki/Ghana' },
  				  { display_name: 'Gibraltar', key: 'gibraltar', wikiUrl: '/wiki/Gibraltar' },
  				  { display_name: 'Greece', key: 'greece', wikiUrl: '/wiki/Greece' },
  				  { display_name: 'Greenland', key: 'greenland', wikiUrl: '/wiki/Greenland' },
  				  { display_name: 'Grenada', key: 'grenada', wikiUrl: '/wiki/Grenada' },
  				  { display_name: 'Guadeloupe', key: 'guadeloupe', wikiUrl: '/wiki/Guadeloupe' },
  				  { display_name: 'Guam', key: 'guam', wikiUrl: '/wiki/Guam' },
  				  { display_name: 'Guatemala', key: 'guatemala', wikiUrl: '/wiki/Guatemala' },
  				  { display_name: 'Guernsey', key: 'guernsey', wikiUrl: '/wiki/Guernsey' },
  				  { display_name: 'Guinea', key: 'guinea', wikiUrl: '/wiki/Guinea' },
  				  { display_name: 'Guinea-Bissau', key: 'guinea_bissau', wikiUrl: '/wiki/Guinea-Bissau' },
  				  { display_name: 'Guyana', key: 'guyana', wikiUrl: '/wiki/Guyana' },
  				  { display_name: 'Haiti', key: 'haiti', wikiUrl: '/wiki/Haiti' },
  				  { display_name: 'Heard Island and Mcdonald Islands', key: 'heard_island_and_mcdonald_islands', wikiUrl: '/wiki/Heard_Island_and_McDonald_Islands' },
  				  { display_name: 'Honduras', key: 'honduras', wikiUrl: '/wiki/Honduras' },
  				  { display_name: 'Hong Kong', key: 'hong_kong', wikiUrl: '/wiki/Hong_Kong' },
  				  { display_name: 'Hungary', key: 'hungary', wikiUrl: '/wiki/Hungary' },
  				  { display_name: 'Iceland', key: 'iceland', wikiUrl: '/wiki/Iceland' },
  				  { display_name: 'India', key: 'india', wikiUrl: '/wiki/India' },
  				  { display_name: 'Indonesia', key: 'indonesia', wikiUrl: '/wiki/Indonesia' },
  				  { display_name: 'Iran', key: 'iran', wikiUrl: '/wiki/Iran' },
  				  { display_name: 'Iraq', key: 'iraq', wikiUrl: '/wiki/Iraq' },
  				  { display_name: 'Iraqi Kurdistan', key: 'iraqi_kurdistan', wikiUrl: '/wiki/Iraqi_Kurdistan' },
  				  { display_name: 'Ireland', key: 'ireland', wikiUrl: '/wiki/Republic_of_Ireland' },
  				  { display_name: 'Isle of Man', key: 'isle_of_man', wikiUrl: '/wiki/Isle_of_Man' },
  				  { display_name: 'Israel', key: 'israel', wikiUrl: '/wiki/Israel' },
  				  { display_name: 'Italy', key: 'italy', wikiUrl: '/wiki/Italy' },
  				  { display_name: 'Jamaica', key: 'jamaica', wikiUrl: '/wiki/Jamaica' },
  				  { display_name: 'Japan', key: 'japan', wikiUrl: '/wiki/Japan' },
  				  { display_name: 'Jersey', key: 'jersey', wikiUrl: '/wiki/Jersey' },
  				  { display_name: 'Jordan', key: 'jordan', wikiUrl: '/wiki/Jordan' },
  				  { display_name: 'Kazakhstan', key: 'kazakhstan', wikiUrl: '/wiki/Kazakhstan' },
  				  { display_name: 'Kenya', key: 'kenya', wikiUrl: '/wiki/Kenya' },
  				  { display_name: 'Kiribati', key: 'kiribati', wikiUrl: '/wiki/Kiribati' },
  				  { display_name: 'Kosovo', key: 'kosovo', wikiUrl: '/wiki/Kosovo' },
  				  { display_name: 'Kuwait', key: 'kuwait', wikiUrl: '/wiki/Kuwait' },
  				  { display_name: 'Kyrgyzstan', key: 'kyrgyzstan', wikiUrl: '/wiki/Kyrgyzstan' },
  				  { display_name: 'Laos', key: 'laos', wikiUrl: '/wiki/Laos' },
  				  { display_name: 'Latvia', key: 'latvia', wikiUrl: '/wiki/Latvia' },
  				  { display_name: 'Lebanon', key: 'lebanon', wikiUrl: '/wiki/Lebanon' },
  				  { display_name: 'Lesotho', key: 'lesotho', wikiUrl: '/wiki/Lesotho' },
  				  { display_name: 'Liberia', key: 'liberia', wikiUrl: '/wiki/Liberia' },
  				  { display_name: 'Libya', key: 'libya', wikiUrl: '/wiki/Libya' },
  				  { display_name: 'Liechtenstein', key: 'liechtenstein', wikiUrl: '/wiki/Liechtenstein' },
  				  { display_name: 'Lithuania', key: 'lithuania', wikiUrl: '/wiki/Lithuania' },
  				  { display_name: 'Luxembourg', key: 'luxembourg', wikiUrl: '/wiki/Luxembourg' },
  				  { display_name: 'Macau', key: 'macau', wikiUrl: '/wiki/Macau' },
  				  { display_name: 'Macedonia', key: 'macedonia', wikiUrl: '/wiki/Republic_of_Macedonia' },
  				  { display_name: 'Madagascar', key: 'madagascar', wikiUrl: '/wiki/Madagascar' },
  				  { display_name: 'Malawi', key: 'malawi', wikiUrl: '/wiki/Malawi' },
  				  { display_name: 'Malaysia', key: 'malaysia', wikiUrl: '/wiki/Malaysia' },
  				  { display_name: 'Maldives', key: 'maldives', wikiUrl: '/wiki/Maldives' },
  				  { display_name: 'Mali', key: 'mali', wikiUrl: '/wiki/Mali' },
  				  { display_name: 'Malta', key: 'malta', wikiUrl: '/wiki/Malta' },
  				  { display_name: 'Marshall Islands', key: 'marshall_islands', wikiUrl: '/wiki/Marshall_Islands' },
  				  { display_name: 'Martinique', key: 'martinique', wikiUrl: '/wiki/Martinique' },
  				  { display_name: 'Mauritania', key: 'mauritania', wikiUrl: '/wiki/Mauritania' },
  				  { display_name: 'Mauritius', key: 'mauritius', wikiUrl: '/wiki/Mauritius' },
  				  { display_name: 'Mayotte', key: 'mayotte', wikiUrl: '/wiki/Mayotte' },
  				  { display_name: 'Mexico', key: 'mexico', wikiUrl: '/wiki/Mexico' },
  				  { display_name: 'Moldova', key: 'moldova', wikiUrl: '/wiki/Moldova' },
  				  { display_name: 'Monaco', key: 'monaco', wikiUrl: '/wiki/Monaco' },
  				  { display_name: 'Mongolia', key: 'mongolia', wikiUrl: '/wiki/Mongolia' },
  				  { display_name: 'Montenegro', key: 'montenegro', wikiUrl: '/wiki/Montenegro' },
  				  { display_name: 'Montserrat', key: 'montserrat', wikiUrl: '/wiki/Montserrat' },
  				  { display_name: 'Morocco', key: 'morocco', wikiUrl: '/wiki/Morocco' },
  				  { display_name: 'Mozambique', key: 'mozambique', wikiUrl: '/wiki/Mozambique' },
  				  { display_name: 'Myanmar (Burma)', key: 'myanmar', wikiUrl: '/wiki/Burma' },
  				  { display_name: 'Nagorno-Karabakh', key: 'nagorno_karabakh', wikiUrl: '/wiki/Nagorno-Karabakh_Republic' }, //
  				  { display_name: 'Namibia', key: 'namibia', wikiUrl: '/wiki/Namibia' },
  				  { display_name: 'Nauru', key: 'nauru', wikiUrl: '/wiki/Nauru' },
  				  { display_name: 'Nepal', key: 'nepal', wikiUrl: '/wiki/Nepal' },
  				  { display_name: 'Netherlands', key: 'netherlands', wikiUrl: '/wiki/Kingdom_of_the_Netherlands' },
  				  { display_name: 'New Caledonia', key: 'new_caledonia', wikiUrl: 'wiki/New_Caledonia' },
  				  { display_name: 'New Zealand', key: 'new_zealand', wikiUrl: '/wiki/New_Zealand' },
  				  { display_name: 'Nicaragua', key: 'nicaragua', wikiUrl: '/wiki/Nicaragua' },
  				  { display_name: 'Niger', key: 'niger', wikiUrl: '/wiki/Niger' },
  				  { display_name: 'Nigeria', key: 'nigeria', wikiUrl: '/wiki/Nigeria' },
  				  { display_name: 'Niue', key: 'niue', wikiUrl: '/wiki/Niue' },
  				  { display_name: 'Norfolk Island', key: 'norfolk_island', wikiUrl: '/wiki/Norfolk_Island' },
  				  { display_name: 'North Korea', key: 'north_korea', wikiUrl: '/wiki/North_Korea' },
  				  { display_name: 'Northern Cyprus', key: 'northern_cyprus', wikiUrl: '/wiki/Northern_Cyprus' },//
  				  { display_name: 'Northern Mariana Islands', key: 'northern_mariana_islands', wikiUrl: '/wiki/Northern_Mariana_Islands' },
  				  { display_name: 'Norway', key: 'norway', wikiUrl: '/wiki/Norway' },
  				  { display_name: 'Oman', key: 'oman', wikiUrl: '/wiki/Oman' },
  				  { display_name: 'Pakistan', key: 'pakistan', wikiUrl: '/wiki/Pakistan' },
  				  { display_name: 'Palau', key: 'palau', wikiUrl: '/wiki/Palau' },
  				  { display_name: 'Palestine', key: 'palestine', wikiUrl: '/wiki/State_of_Palestine' },
  				  { display_name: 'Panama', key: 'panama', wikiUrl: '/wiki/Panama' },
  				  { display_name: 'Papua New Guinea', key: 'papua_new_guinea', wikiUrl: '/wiki/Papua_New_Guinea' },
  				  { display_name: 'Paraguay', key: 'paraguay', wikiUrl: '/wiki/Paraguay' },
  				  { display_name: 'People\'s Republic of China', key: 'peoples_republic_of_china', wikiUrl: '/wiki/China' },
  				  { display_name: 'Peru', key: 'peru', wikiUrl: '/wiki/Peru' },
  				  { display_name: 'Philippines', key: 'philippines', wikiUrl: '/wiki/Philippines' },
  				  { display_name: 'Pitcairn Islands', key: 'pitcairn_islands', wikiUrl: '/wiki/Pitcairn_Islands' },
  				  { display_name: 'Poland', key: 'poland', wikiUrl: '/wiki/Poland' },
  				  { display_name: 'Portugal', key: 'portugal', wikiUrl: '/wiki/Portugal' },
  				  { display_name: 'Puerto Rico', key: 'puerto_rico', wikiUrl: '/wiki/Puerto_Rico' },
  				  { display_name: 'Qatar', key: 'qatar', wikiUrl: '/wiki/Qatar' },
  				  { display_name: 'R&eacute;union', key: 'reunion', wikiUrl: '/wiki/R%C3%A9union' },
  				  { display_name: 'Republic of China (Taiwan)', key: 'taiwan', wikiUrl: '/wiki/Taiwan' },
  				  { display_name: 'Romania', key: 'romania', wikiUrl: '/wiki/Romania' },
  				  { display_name: 'Russia', key: 'russia', wikiUrl: '/wiki/Russia' },
  				  { display_name: 'Rwanda', key: 'rwanda', wikiUrl: '/wiki/Rwanda' },
  				  { display_name: 'S&atilde;o Tom&eacute; and Pr&iacute;ncipe', key: 'sao_tome_and_principe', wikiUrl: '/wiki/S%C3%A3o_Tom%C3%A9_and_Pr%C3%ADncipe' },
  				  { display_name: 'Sahrawi Arab Democratic Republic', key: 'sahrawi_arab_democratic_republic', wikiUrl: '/wiki/Sahrawi_Arab_Democratic_Republic' },//
  				  { display_name: 'Saint Barth&eacute;lemy', key: 'saint_barthelemy', wikiUrl: '/wiki/Saint_Barth%C3%A9lemy' },//
  				  { display_name: 'Saint Helena', key: 'saint_helena', wikiUrl: '/wiki/Saint_Helena' },
  				  { display_name: 'Saint Kitts and Nevis', key: 'saint_kitts_and_nevis', wikiUrl: '/wiki/Saint_Kitts_and_Nevis' },
  				  { display_name: 'Saint Lucia', key: 'saint_lucia', wikiUrl: '/wiki/Saint_Lucia' },
  				  { display_name: 'Saint Martin', key: 'saint_martin', wikiUrl: '/wiki/Collectivity_of_Saint_Martin' },
  				  { display_name: 'Saint Vincent and the Grenadines', key: 'saint_vincent_and_the_grenadines', wikiUrl: '/wiki/Saint_Vincent_and_the_Grenadines' },
  				  { display_name: 'Saint-Pierre and Miquelon', key: 'saint_pierre_and_miquelon', wikiUrl: '/wiki/Saint_Pierre_and_Miquelon' },
  				  { display_name: 'Samoa', key: 'samoa', wikiUrl: '/wiki/Samoa' },
  				  { display_name: 'San Marino', key: 'san_marino', wikiUrl: '/wiki/San_Marino' },
  				  { display_name: 'Saudi Arabia', key: 'saudi_arabia', wikiUrl: '/wiki/Saudi_Arabia' },
  				  { display_name: 'Scotland', key: 'scotland', wikiUrl: '/wiki/Scotland' },
  				  { display_name: 'Senegal', key: 'senegal', wikiUrl: '/wiki/Senegal' },
  				  { display_name: 'Serbia', key: 'serbia', wikiUrl: '/wiki/Serbia' },
  				  { display_name: 'Seychelles', key: 'seychelles', wikiUrl: '/wiki/Seychelles' },
  				  { display_name: 'Sierra Leone', key: 'sierra_leone', wikiUrl: '/wiki/Sierra_Leone' },
  				  { display_name: 'Singapore', key: 'singapore', wikiUrl: '/wiki/Singapore' },
  				  { display_name: 'Sint Maarten', key: 'sint_maarten', wikiUrl: '/wiki/Sint_Maarten' },//
  				  { display_name: 'Slovakia', key: 'slovakia', wikiUrl: '/wiki/Slovakia' },
  				  { display_name: 'Slovenia', key: 'slovenia', wikiUrl: '/wiki/Slovenia' },
  				  { display_name: 'Solomon Islands', key: 'solomon_islands', wikiUrl: '/wiki/Solomon_Islands' },
  				  { display_name: 'Somalia', key: 'somalia', wikiUrl: '/wiki/Somalia' },
  				  { display_name: 'Somaliland', key: 'somaliland', wikiUrl: '/wiki/Somaliland' },
  				  { display_name: 'South Africa', key: 'south_africa', wikiUrl: '/wiki/South_Africa' },
  				  { display_name: 'South Georgia and the South Sandwich Islands', key: 'south_georgia_and_the_south_sandwich_islands', wikiUrl: '/wiki/South_Georgia_and_the_South_Sandwich_Islands' },
  				  { display_name: 'South Korea', key: 'south_korea', wikiUrl: '/wiki/South_Korea' },
  				  { display_name: 'South Ossetia', key: 'south_ossetia', wikiUrl: '/wiki/South_Ossetia' },//
  				  { display_name: 'South Sudan', key: 'south_sudan', wikiUrl: '/wiki/South_Sudan' },//
  				  { display_name: 'Spain', key: 'spain', wikiUrl: '/wiki/Spain' },
  				  { display_name: 'Sri Lanka', key: 'sri_lanka', wikiUrl: '/wiki/Sri_Lanka' },
  				  { display_name: 'Sudan', key: 'sudan', wikiUrl: '/wiki/Sudan' },
  				  { display_name: 'Suriname', key: 'suriname', wikiUrl: '/wiki/Suriname' },
  				  { display_name: 'Svalbard and Jan Mayen', key: 'svalbard_and_jan_mayen', wikiUrl: '/wiki/Svalbard_and_Jan_Mayen' },
  				  { display_name: 'Swaziland', key: 'swaziland', wikiUrl: '/wiki/Swaziland' },
  				  { display_name: 'Sweden', key: 'sweden', wikiUrl: '/wiki/Sweden' },
  				  { display_name: 'Switzerland', key: 'switzerland', wikiUrl: '/wiki/Switzerland' },
  				  { display_name: 'Syria', key: 'syria', wikiUrl: '/wiki/Syria' },
  				  { display_name: 'Syrian Kurdistan', key: 'syrian_kurdistan', wikiUrl: '/wiki/Syrian_Kurdistan' },
  				  { display_name: 'Tajikistan', key: 'tajikistan', wikiUrl: '/wiki/Tajikistan' },
  				  { display_name: 'Tanzania', key: 'tanzania', wikiUrl: '/wiki/Tanzania' },
  				  { display_name: 'Thailand', key: 'thailand', wikiUrl: '/wiki/Thailand' },
  				  { display_name: 'The Bahamas', key: 'bahamas', wikiUrl: '/wiki/The_Bahamas' },
  				  { display_name: 'The Gambia', key: 'the_gambia', wikiUrl: '/wiki/The_Gambia' },
  				  { display_name: 'Timor-Leste (East Timor)', key: 'east_timor', wikiUrl: '/wiki/East_Timor' },//
  				  { display_name: 'Togo', key: 'togo', wikiUrl: '/wiki/Togo' },
  				  { display_name: 'Tokelau', key: 'tokelau', wikiUrl: '/wiki/Tokelau' },
  				  { display_name: 'Tonga', key: 'tonga', wikiUrl: '/wiki/Tonga' },
  				  { display_name: 'Transnistria', key: 'transnistria', wikiUrl: '/wiki/Transnistria' },
  				  { display_name: 'Trinidad and Tobago', key: 'trinidad_and_tobago', wikiUrl: '/wiki/Trinidad_and_Tobago' },
  				  { display_name: 'Tunisia', key: 'tunisia', wikiUrl: '/wiki/Tunisia' },
  				  { display_name: 'Turkey', key: 'turkey', wikiUrl: '/wiki/Turkey' },
  				  { display_name: 'Turkmenistan', key: 'turkmenistan', wikiUrl: '/wiki/Turkmenistan' },
  				  { display_name: 'Turks and Caicos Islands', key: 'turks_and_caicos_islands', wikiUrl: '/wiki/Turks_and_Caicos_Islands' },
  				  { display_name: 'Tuvalu', key: 'tuvalu', wikiUrl: '/wiki/Tuvalu' },
  				  { display_name: 'Uganda', key: 'uganda', wikiUrl: '/wiki/Uganda' },
  				  { display_name: 'Ukraine', key: 'ukraine', wikiUrl: '/wiki/Ukraine' },
  				  { display_name: 'United Arab Emirates', key: 'united_arab_emirates', wikiUrl: '/wiki/United_Arab_Emirates' },
  				  { display_name: 'United Kingdom', key: 'united_kingdom', wikiUrl: '/wiki/United_Kingdom' },
  				  { display_name: 'United States Minor Outlying Islands', key: 'united_states_minor_outlying_islands', wikiUrl: '/wiki/United_States_Minor_Outlying_Islands' },
  				  { display_name: 'United States Virgin Islands', key: 'united_states_virgin_islands', wikiUrl: '/wiki/United_States_Virgin_Islands' },
  				  { display_name: 'United States of America', key: 'united_states', wikiUrl: '/wiki/United_States' },//
  				  { display_name: 'Uruguay', key: 'uruguay', wikiUrl: '/wiki/Uruguay' },
  				  { display_name: 'Uzbekistan', key: 'uzbekistan', wikiUrl: '/wiki/Uzbekistan' },
  				  { display_name: 'Vanuatu', key: 'vanuatu', wikiUrl: '/wiki/Vanuatu' },
  				  { display_name: 'Vatican City', key: 'vatican_city', wikiUrl: '/wiki/Vatican_City' },
  				  { display_name: 'Venezuela', key: 'venezuela', wikiUrl: '/wiki/Venezuela' },
  				  { display_name: 'Vietnam', key: 'vietnam', wikiUrl: '/wiki/Vietnam' },
  				  { display_name: 'Wales', key: 'wales', wikiUrl: '/wiki/Wales' },
  				  { display_name: 'Wallis and Futuna', key: 'wallis_and_futuna', wikiUrl: '/wiki/Wallis_and_Futuna' },
  				  { display_name: 'Yemen', key: 'yemen', wikiUrl: '/wiki/Yemen' },
  				  { display_name: 'Zambia', key: 'zambia', wikiUrl: '/wiki/Zambia' },
  				  { display_name: 'Zimbabwe', key: 'zimbabwe', wikiUrl: '/wiki/Zimbabwe' } ]

function loop() {
	for (var i = 0; i < countries.length; i++) {
		console.log('.' + countries[i]['key'] + ' ' + countries[i]['key'] + '*')
	}
}

loop()

